# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\x12\x04user\x1a\x1bgoogle/protobuf/empty.proto\"\xbc\x03\n\nCustomUser\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x12\n\nlast_login\x18\x03 \x01(\t\x12\x14\n\x0cis_superuser\x18\x04 \x01(\x08\x12\x10\n\x08is_staff\x18\x05 \x01(\x08\x12\x11\n\tis_active\x18\x06 \x01(\x08\x12\x13\n\x0b\x64\x61te_joined\x18\x07 \x01(\t\x12\r\n\x05phone\x18\x08 \x01(\t\x12\x12\n\nfirst_name\x18\t \x01(\t\x12\x11\n\tlast_name\x18\n \x01(\t\x12\r\n\x05\x65mail\x18\x0b \x01(\t\x12\x15\n\rnational_code\x18\x0c \x01(\t\x12\x12\n\nbirth_date\x18\r \x01(\t\x12\x0e\n\x06gender\x18\x0e \x01(\x05\x12\x13\n\x0bnationality\x18\x0f \x01(\t\x12\x1a\n\x12notification_token\x18\x10 \x01(\t\x12\x0f\n\x07os_type\x18\x11 \x01(\t\x12\x18\n\x10\x64\x65vice_unique_id\x18\x12 \x01(\t\x12\x12\n\ncreated_at\x18\x13 \x01(\t\x12\x12\n\nupdated_at\x18\x14 \x01(\t\x12\x0e\n\x06groups\x18\x15 \x03(\x05\x12\x18\n\x10user_permissions\x18\x16 \x03(\x05\"\x17\n\x15\x43ustomUserListRequest\"\'\n\x19\x43ustomUserRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xa9\x02\n\x14\x43ustomUserController\x12\x39\n\x04List\x12\x1b.user.CustomUserListRequest\x1a\x10.user.CustomUser\"\x00\x30\x01\x12.\n\x06\x43reate\x12\x10.user.CustomUser\x1a\x10.user.CustomUser\"\x00\x12?\n\x08Retrieve\x12\x1f.user.CustomUserRetrieveRequest\x1a\x10.user.CustomUser\"\x00\x12.\n\x06Update\x12\x10.user.CustomUser\x1a\x10.user.CustomUser\"\x00\x12\x35\n\x07\x44\x65stroy\x12\x10.user.CustomUser\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_CUSTOMUSER = DESCRIPTOR.message_types_by_name['CustomUser']
_CUSTOMUSERLISTREQUEST = DESCRIPTOR.message_types_by_name['CustomUserListRequest']
_CUSTOMUSERRETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['CustomUserRetrieveRequest']
CustomUser = _reflection.GeneratedProtocolMessageType('CustomUser', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMUSER,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.CustomUser)
  })
_sym_db.RegisterMessage(CustomUser)

CustomUserListRequest = _reflection.GeneratedProtocolMessageType('CustomUserListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMUSERLISTREQUEST,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.CustomUserListRequest)
  })
_sym_db.RegisterMessage(CustomUserListRequest)

CustomUserRetrieveRequest = _reflection.GeneratedProtocolMessageType('CustomUserRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMUSERRETRIEVEREQUEST,
  '__module__' : 'proto.user_pb2'
  # @@protoc_insertion_point(class_scope:user.CustomUserRetrieveRequest)
  })
_sym_db.RegisterMessage(CustomUserRetrieveRequest)

_CUSTOMUSERCONTROLLER = DESCRIPTOR.services_by_name['CustomUserController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMUSER._serialized_start=56
  _CUSTOMUSER._serialized_end=500
  _CUSTOMUSERLISTREQUEST._serialized_start=502
  _CUSTOMUSERLISTREQUEST._serialized_end=525
  _CUSTOMUSERRETRIEVEREQUEST._serialized_start=527
  _CUSTOMUSERRETRIEVEREQUEST._serialized_end=566
  _CUSTOMUSERCONTROLLER._serialized_start=569
  _CUSTOMUSERCONTROLLER._serialized_end=866
# @@protoc_insertion_point(module_scope)
