# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\x07\x61\x63\x63ount\x1a\x1bgoogle/protobuf/empty.proto\":\n\x08UserBase\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"\x15\n\x13UserBaseListRequest\"%\n\x17UserBaseRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xb0\x02\n\x12UserBaseController\x12;\n\x04List\x12\x1c.account.UserBaseListRequest\x1a\x11.account.UserBase\"\x00\x30\x01\x12\x30\n\x06\x43reate\x12\x11.account.UserBase\x1a\x11.account.UserBase\"\x00\x12\x41\n\x08Retrieve\x12 .account.UserBaseRetrieveRequest\x1a\x11.account.UserBase\"\x00\x12\x30\n\x06Update\x12\x11.account.UserBase\x1a\x11.account.UserBase\"\x00\x12\x36\n\x07\x44\x65stroy\x12\x11.account.UserBase\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_USERBASE = DESCRIPTOR.message_types_by_name['UserBase']
_USERBASELISTREQUEST = DESCRIPTOR.message_types_by_name['UserBaseListRequest']
_USERBASERETRIEVEREQUEST = DESCRIPTOR.message_types_by_name['UserBaseRetrieveRequest']
UserBase = _reflection.GeneratedProtocolMessageType('UserBase', (_message.Message,), {
  'DESCRIPTOR' : _USERBASE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserBase)
  })
_sym_db.RegisterMessage(UserBase)

UserBaseListRequest = _reflection.GeneratedProtocolMessageType('UserBaseListRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERBASELISTREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserBaseListRequest)
  })
_sym_db.RegisterMessage(UserBaseListRequest)

UserBaseRetrieveRequest = _reflection.GeneratedProtocolMessageType('UserBaseRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERBASERETRIEVEREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:account.UserBaseRetrieveRequest)
  })
_sym_db.RegisterMessage(UserBaseRetrieveRequest)

_USERBASECONTROLLER = DESCRIPTOR.services_by_name['UserBaseController']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERBASE._serialized_start=55
  _USERBASE._serialized_end=113
  _USERBASELISTREQUEST._serialized_start=115
  _USERBASELISTREQUEST._serialized_end=136
  _USERBASERETRIEVEREQUEST._serialized_start=138
  _USERBASERETRIEVEREQUEST._serialized_end=175
  _USERBASECONTROLLER._serialized_start=178
  _USERBASECONTROLLER._serialized_end=482
# @@protoc_insertion_point(module_scope)
