# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0e\x61uthentication\"*\n\x04\x41uth\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x14\n\x06UserPk\x12\n\n\x02pk\x18\x01 \x01(\x03\x32P\n\x0e\x41uthentication\x12>\n\x0e\x41uthentication\x12\x14.authentication.Auth\x1a\x16.authentication.UserPkb\x06proto3')



_AUTH = DESCRIPTOR.message_types_by_name['Auth']
_USERPK = DESCRIPTOR.message_types_by_name['UserPk']
Auth = _reflection.GeneratedProtocolMessageType('Auth', (_message.Message,), {
  'DESCRIPTOR' : _AUTH,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authentication.Auth)
  })
_sym_db.RegisterMessage(Auth)

UserPk = _reflection.GeneratedProtocolMessageType('UserPk', (_message.Message,), {
  'DESCRIPTOR' : _USERPK,
  '__module__' : 'auth_pb2'
  # @@protoc_insertion_point(class_scope:authentication.UserPk)
  })
_sym_db.RegisterMessage(UserPk)

_AUTHENTICATION = DESCRIPTOR.services_by_name['Authentication']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTH._serialized_start=30
  _AUTH._serialized_end=72
  _USERPK._serialized_start=74
  _USERPK._serialized_end=94
  _AUTHENTICATION._serialized_start=96
  _AUTHENTICATION._serialized_end=176
# @@protoc_insertion_point(module_scope)
